#!/usr/bin/env bash

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

docker create -it \
  --name cpp-starter \
  --mount type=bind,source="$REPO_ROOT",target=/cpp-starter \
  --mount type=bind,source=/etc/localtime,target=/etc/localtime,readonly \
  brikex/cpp-dev:latest bash
